# https://github.com/marketplace/actions/sync-pull-requests-to-azure-boards

name: Sync Pull Request to Azure DevOps

on:
  pull_request:
    types: [opened, edited, closed]
    branches:
      - 'develop'

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-pr-to-work-item@master
        env:
          ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
          github_token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
          ado_organization: 'intershop-com'
          ado_project: 'Products'
          ado_wit: 'Pull Request'
          ado_new_state: 'New'
          ado_active_state: 'Active'
          ado_close_state: 'Closed'
